import crypto from "crypto";
import { env } from "../config/env";
import { redisConnection } from "../config/redis";
import { getSlack, saveSlack, disconnectSlack } from "../models/slack.model";
const scopes="chat:write,incoming-webhook";
export const getSlackAuthUrl=async(userId:string)=>{const state=crypto.randomBytes(24).toString("hex");await redisConnection.set(`slack-state:${state}`,userId,"EX",600);const p=new URLSearchParams({client_id:env.SLACK_CLIENT_ID,scope:scopes,redirect_uri:env.SLACK_REDIRECT_URI,state});return `https://slack.com/oauth/v2/authorize?${p.toString()}`;};
export const handleSlackCallback=async(code:string,state:string)=>{const userId=await redisConnection.get(`slack-state:${state}`);if(!userId) throw new Error("Invalid or expired Slack state");await redisConnection.del(`slack-state:${state}`);const p=new URLSearchParams({client_id:env.SLACK_CLIENT_ID,client_secret:env.SLACK_CLIENT_SECRET,code,redirect_uri:env.SLACK_REDIRECT_URI});const r=await fetch("https://slack.com/api/oauth.v2.access",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:p});const data=await r.json() as any;if(!data.ok) throw new Error(data.error||"Slack OAuth failed");await saveSlack(userId,data.team?.id??null,data.access_token,data.incoming_webhook?.channel_id??null,data.incoming_webhook?.url??null);return userId;};
export const disconnectSlackForUser=async(userId:string)=>disconnectSlack(userId);
export const notifyRateLimit=async(userId:string,senderId:string,limit:number)=>{const s=await getSlack(userId);if(!s)return;if(s.webhook_url){const r=await fetch(s.webhook_url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:`⚠️ Email rate limit reached\nSender: ${senderId}\nHourly limit: ${limit}\nRemaining emails will continue in the next available hourly window.`})});if(!r.ok) throw new Error("Slack webhook failed");return;}if(s.channel_id){const r=await fetch("https://slack.com/api/chat.postMessage",{method:"POST",headers:{Authorization:`Bearer ${s.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({channel:s.channel_id,text:`⚠️ Email rate limit reached\nSender: ${senderId}\nHourly limit: ${limit}\nRemaining emails will continue in the next available hourly window.`})});const data=await r.json() as any;if(!data.ok)throw new Error(data.error||"Slack message failed");}};
